### ISSUE TITLE
Failed at the tinder-scraper@0.2.1 start script. No file or directory.

### ISSUE THREAD

**Issue by neeooh** [gcwelborn/tinder-scraper#17]
I can assure you that I successfully cloned the repo, installed all dependencies and have a correct FB ID and Auth Token. 
I also run PowerShell with Admin privileges.
Can anyone help me? I'd love to run this program :( 
Thanks in advance! 🥇 

> PS C:\tinder-scraper> npm start
> 
> tinder-scraper@0.2.1 start C:\tinder-scraper
> node lib/index.js
> 
> fs.js:892
>   return binding.mkdir(pathModule._makeLong(path),
>                  ^
> 
> Error: ENOENT: no such file or directory, mkdir 'C:\tinder-scraper\data\2017-11-701:26:24'
>     at Object.fs.mkdirSync (fs.js:892:18)
>     at Object.<anonymous> (C:\tinder-scraper\lib\fileHelpers.js:19:9)
[2017-11-07T01_26_24_594Z-debug.log](https://github.com/gcwelborn/tinder-scraper/files/1448355/2017-11-07T01_26_24_594Z-debug.log)

>     at Module._compile (module.js:624:30)
>     at Object.Module._extensions..js (module.js:635:10)
>     at Module.load (module.js:545:32)
>     at tryModuleLoad (module.js:508:12)
>     at Function.Module._load (module.js:500:3)
>     at Module.require (module.js:568:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (C:\tinder-scraper\lib\index.js:1:80)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! tinder-scraper@0.2.1 start: `node lib/index.js`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the tinder-scraper@0.2.1 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     C:\Users\ma\AppData\Roaming\npm-cache\_logs\2017-11-07T01_26_24_594Z-debug.log
> PS C:\tinder-scraper>

**Comment by Sanguinius1** [comment]
Hey, i think i had the same error. maybe this answer from user @sophisticaedcode helps: 

I guess it's not making the timestamp folder? I tried playing around but I couldn't figure the code to do it myself.
Yeah, I figured it out. You can't make folders with special characters such as colons in them on Windows, and the timestamp has colons in it so the folder just doesn't get made.

I just added the last two lines to make them into underscores instead of colons in the fileHelpers.js

export const TIMESTAMP = (
	new Date()
		.toLocaleString()
		.replace(new RegExp('/', 'g'), '.')
		.replace(new RegExp(', ', 'g'), '-')
		.replace(' ', '')
		.replace(':', '_')
		.replace(':', '_')
);
 

(see in the thread error running node dist/index.js #8)

hope this helps.

**Comment by Sanguinius1** [comment]
Btw, if you can help me with a little issue i would be really grateful. somehow all the steps have worked so far (except the last as i am experiencing an Error in Authorization) but i couldnt clone the Repo, or am unsure if it has worked. I am using Anaconda Prompt and when i enter: $ git clone https://github.com/tinderjs/tinder-scraper.git 
it tells me that "$" is a bad request or sth...
Same happens when i leave out the $ and start the command with "git". 
O.o any idea? 

best wishes, 
Dominic

**Comment by Sanguinius1** [comment]
Funny, now, after havin installed GitHub and gitBash on my PC (before i sued Anaconda Prompt) I ma getting the same error as you @neeooh .... hmmmm :-/ (Note, i use windows 10)

**Comment by Sanguinius1** [comment]
@neeooh Hey! So, now I found the error. Maybe that applies to you too. Previously I worked with Anaconda Prompt from my C:/documents/tinder-scraper pathway, where, in the config.js I had done everything according to @gcwelborn manual. Now, when I installed GitHub on my PC and loaded the Repository from there/opened it in the command prompt, naturally it used the pathway C:/documents/GitHub/tinder-scraper with the default config-scraper.js . So I had to fill in the FB-ID and the Auth-Token and voila. it works. 
Hope this helps you mate. 
Best wishes
Dominic

**Comment by neeooh** [comment]
HEy @Sanguinius1 Thanks so much for your answer! I edited fileHelpers.js and it fixed the problem! :) I then  had another "Error in Authorization" even though I had correct FB_ID and Access_token. I realized that it was my VPN causing the problem. I turned it off and the app works like charm! Thanks again :) 👍
