### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by kgoldmann** [gcwelborn/tinder-scraper#3]
I've been encountering issues with the scraper stopping with the following error message after about 10 minutes of activity. Any idea what could be causing it?

2016-04-09 10:44:22 names of users scraped: Kitty : Karina : Maggie : Margarita : Lena : Tam : 2016-04-09 10:44:22: 6 matches scraped...
2016-04-09 10:44:31: Getting new match stack...
2016-04-09 10:44:31: new match stack received...
2016-04-09 10:44:31 names of users scraped: /Users/Dex/Library/Mobile Documents/tinder-scraper/app.js:46
      data.results.forEach(function (match) {
                  ^

TypeError: Cannot read property 'forEach' of undefined
    at /Users/Dex/Library/Mobile Documents/tinder-scraper/app.js:46:19
    at Request._callback (/Users/Dex/Library/Mobile Documents/tinder-scraper/node_modules/tinderjs/tinder.js:93:9)
    at Request.self.callback (/Users/Dex/Library/Mobile Documents/tinder-scraper/node_modules/request/request.js:121:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/Dex/Library/Mobile Documents/tinder-scraper/node_modules/request/request.js:978:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/Dex/Library/Mobile Documents/tinder-scraper/node_modules/request/request.js:929:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! tinder-scraper@0.0.1 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tinder-scraper@0.0.1 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tinder-scraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls tinder-scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Dex/Library/Mobile Documents/tinder-scraper/npm-debug.log

**Comment by gcwelborn** [comment]
Made significant changes to tinder-scraper. could you try it out again and see if your error persists?

**Comment by kgoldmann** [comment]
So far, so good! I have a suspicion that the error is connected to running out of matches in a city, because it repeatedly shows up after a certain threshold (different for each location).

**Comment by gcwelborn** [comment]
I ran across the situation of not having any matches and also receiving a 'recs timeout' status from tinder. There should now be a console message if either of these scenarios happen.

**Comment by kgoldmann** [comment]
tinder-scraper seems to handle this situation much better now and eventually resumes the scraping. Great job!

2016-04-11 22:58:56: Stephanie's data was collected
2016-04-11 22:58:56: 3 matches scraped...
tinder-scraper: no error received, yet no results either - try expanding your search radius in the mobile app
2016-04-11 22:59:16: Amy's data was collected
2016-04-11 22:59:16: Alexandra's data was collected
2016-04-11 22:59:16: Ria's data was collected
2016-04-11 22:59:16: Beth's data was collected
2016-04-11 22:59:16: 4 matches scraped...

**Comment by gcwelborn** [comment]
@kgoldmann awesome, glad to hear
