### ISSUE TITLE
Ubuntu Installation error

### ISSUE THREAD

**Issue by JohnSmith20018** [gcwelborn/tinder-scraper#7]
Running `npm install` works fine on Ubuntu, but the next steps fail:

```
   │ ├─┬ combined-stream@1.0.5 
    │ │ └── delayed-stream@1.0.0 
    │ └─┬ mime-types@2.1.15 
    │   └── mime-db@1.27.0 
    ├── formidable@1.0.17 
    ├── methods@1.1.2 
    ├── mime@1.3.4 
    ├── qs@2.3.3 
    ├─┬ readable-stream@1.0.27-1 
    │ ├── core-util-is@1.0.2 
    │ ├── isarray@0.0.1 
    │ └── string_decoder@0.10.31 
    └── reduce-component@1.0.1 

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1
ubuntu@ubuntu-VirtualBox:~/tinder-scraper$ npm start

> tinder-scraper@0.2.1 start /home/ubuntu/tinder-scraper
> clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js

/usr/bin/env: ‘node’: No such file or directory


npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! tinder-scraper@0.2.1 start: `clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the tinder-scraper@0.2.1 start script 'clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tinder-scraper package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tinder-scraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tinder-scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/tinder-scraper/npm-debug.log
ubuntu@ubuntu-VirtualBox:~/tinder-scraper$ 
```

**Comment by gcwelborn** [comment]
can you try running the commands individually?
i.e. `babel lib/ -d dist/` then `node dist/index.js`

**Comment by sophisticatedcode** [comment]
`[npm-debug.txt](https://github.com/gcwelborn/tinder-scraper/files/985723/npm-debug.txt)`

**Comment by sophisticatedcode** [comment]
I'm getting roughly the same error, though I'm on Windows 8.1. Ran `npm install` and it worked, this is the result of running `npm start`
```
C:\Users\Elizabeth\Desktop\tinder2>npm start

> tinder-scraper@0.2.0 start C:\Users\Elizabeth\Desktop\tinder2
> clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js

'clear' is not recognized as an internal or external command,
operable program or batch file.
'rm' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! tinder-scraper@0.2.0 start: `clear & rm -rf dist/ && babel lib/ -d dist
/ && node dist/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tinder-scraper@0.2.0 start script 'clear & rm -rf dist/ &
& babel lib/ -d dist/ && node dist/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tinder-scraper packag
e,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     clear & rm -rf dist/ && babel lib/ -d dist/ && node dist/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tinder-scraper
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tinder-scraper
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Elizabeth\Desktop\tinder2\npm-debug.log
```

Here is trying to run `babel lib/ -d dist/`
```
C:\Users\Elizabeth\Desktop\tinder2>babel lib/ -d dist/
lib\config.scraper.js -> dist\config.scraper.js
lib\fileHelpers.js -> dist\fileHelpers.js
lib\index.js -> dist\index.js
lib\tinderHelpers.js -> dist\tinderHelpers.js
```
And `node dist/index.js`
```
C:\Users\Elizabeth\Desktop\tinder2>node dist/index.js
C:\Users\Elizabeth\Desktop\tinder2\dist\index.js:1
(function (exports, require, module, __filename, __dirname) { import { writeOut
} from './fileHelpers';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:390:7)
    at startup (bootstrap_node.js:150:9)
```
