### ISSUE TITLE
error running node dist/index.js

### ISSUE THREAD

**Issue by sophisticatedcode** [gcwelborn/tinder-scraper#8]
I'm getting an error when running `node dist/index.js`
```
$ node dist/index.js
fs.js:895
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir 'C:\users\elizabeth\desktop\tinder2\data\2017-5-1103:31:01'
    at Object.fs.mkdirSync (fs.js:895:18)
    at Object.<anonymous> (C:\users\elizabeth\desktop\tinder2\dist\fileHelpers.js:27:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\elizabeth\desktop\tinder2\dist\index.js:3:20)
```
I guess it's not making the timestamp folder? I tried playing around but I couldn't figure it out myself.

**Comment by sophisticatedcode** [comment]
Unfortunately my troubles doesn't end there, my auth code isn't being accepted. Not sure why, does it need just the code after "access_token" and before "&" or just everything after "access_token"? I tried both and neither worked, can you show an example please?

```
C:\users\elizabeth\desktop\tinder2\dist\config.scraper.js:12
var AUTH_TOKEN = exports.AUTH_TOKEN = EAAGm0PX4ZCpsBAJz82686R3JTdM6QtAOdRyWIYjoMUOatEZBCuMUDjKZANcX4mJ09xP4r75rlNrhfaR5JFonoy9ZAiKgH54AL5fD6otF5iQvIVsgBvDM0AHVwviDHZAv9y7JKBxCdG7m9wbZCw9v7IFxw5vhABFkoXT06otjsA14hLFWuDe1nbNpGZALx8ms9PQOiytu1QQRC9xeBr5OtvkQGr76gam4VCGtSVDN35dgbZCmnDqG5UBtDeSNQdUogzQZD;
                                      ^

ReferenceError: EAAGm0PX4ZCpsBAJz82686R3JTdM6QtAOdRyWIYjoMUOatEZBCuMUDjKZANcX4mJ09xP4r75rlNrhfaR5JFonoy9ZAiKgH54AL5fD6otF5iQvIVsgBvDM0AHVwviDHZAv9y7JKBxCdG7m9wbZCw9v7IFxw5vhABFkoXT06otjsA14hLFWuDe1nbNpGZALx8ms9PQOiytu1QQRC9xeBr5OtvkQGr76gam4VCGtSVDN35dgbZCmnDqG5UBtDeSNQdUogzQZD is not defined
    at Object.<anonymous> (C:\users\elizabeth\desktop\tinder2\dist\config.scraper.js:12:39)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\users\elizabeth\desktop\tinder2\dist\tinderHelpers.js:16:15)
    at Module._compile (module.js:571:32)
```
